[package]
name = "commons"
version = "0.1.0"

[dependencies]
log = { workspace = true }
log4rs = { workspace = true }
num = { workspace = true }
rmp-serde = { workspace = true }
serde = { workspace = true }