[package]
name = "commons"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1",  features = ["derive"] }
rmp-serde = "1.1.1"
num = "0.4.0"
log = { version = "0.4", features = ["std", "serde"] }
log4rs = { version = "1.2.0"}