[package]
name = "engine-core"
edition.workspace = true
version.workspace = true
authors.workspace = true

[dependencies]
commons = { workspace = true }

log = { workspace = true }
rmp-serde = { workspace = true }
serde = { workspace = true }
timer = { workspace = true }