[package]
name = "engine-core"
version = "0.1.0"

[dependencies]
commons = { workspace = true }

log = { workspace = true }
rmp-serde = { workspace = true }
serde = { workspace = true }
timer = { workspace = true }