[package]
name = "rust_game"
version = "0.1.0"
authors = ["benal"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1",  features = ["derive"]}
rmp-serde = "0.15.0"
log = { version = "0.4", features = ["std", "serde"] }
log4rs = { version = "1"}